### ISSUE TITLE
Add function/description how to start new plot on a deeper level

### ISSUE THREAD

**Issue by mrustl** [KWB-R/kwb.fakin#3]
E.g. data/ instead of Y:/project/wp1/ for multiple paths by skipping the first levels

**Comment by hsonne** [comment]
You can now pass a tree structure that is internally converted back to a vector of paths. Use ’path_tree$subdir_1$subdir_2’ to select a sub-tree at a deeper level and pass that to the plot function.

**Comment by mrustl** [comment]
Great. If documenration is updated how user can add his own check function you should publish a first offical release
