### ISSUE TITLE
Add Zenodo badge in README.(R)md 

### ISSUE THREAD

**Issue by mrustl** [KWB-R/kwb.fakin#5]
Always pointing to lates release: 

[![DOI](https://zenodo.org/badge/136065795.svg)](https://zenodo.org/badge/latestdoi/136065795)

`[![DOI](https://zenodo.org/badge/136065795.svg)](https://zenodo.org/badge/latestdoi/136065795)`

This should be also linked with the released documentation at https://kwb-r.github.io/kwb.fakin

**Comment by hsonne** [comment]
Done.

**Comment by mrustl** [comment]
Yes, but only in the dev version because you increased the version number already. Please also update the docu (locally) for the latest release by resetting the pkg version to 0.3.0 and then just pushing the docs/ folder content!

**Comment by mrustl** [comment]
Now only https://kwb-r.github.io/kwb.fakin/dev/ has the Zenodo badge! 

Release 0.3.0 not -> https://kwb-r.github.io/kwb.fakin

**Comment by hsonne** [comment]
@mrustl Satisfied? https://kwb-r.github.io/kwb.fakin/

**Comment by mrustl** [comment]
Great!
